[package]
name = "todotrust_dev"
readme = "README.md"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3"
tempfile = "3.25.0"
thiserror = "2.0.18"

[[bin]]
name = "todotrust"
path = "src/main.rs"